### ISSUE TITLE
Could not run PIONEER test data

### ISSUE THREAD

**Issue by wangxuann1995** [haiyuan-yu-lab/PIONEER#2]
Hi,

Thanks for providing this amazing tool. I faced some issues when I tried to run it in my cluster.

Follow your instruction I could easily install pioneer in my cluster but when I try to run the test data, I face some  issues:
ImportError: /work/XuanWang#4465/Software/miniconda3/envs/pioneer/lib/python3.8/site-packages/torch_scatter/scatter_cpu.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c108BFloat16EEEPKNS_6detail12TypeMetaDataEv

It seems there are some conflict version between PyTorch and cuda? Could you also help share your yaml file of the PIONNER environment if possible?

Any suggestion is appreciated!

Best
Xuan

**Comment by wangxuann1995** [comment]
Hi,

Environment solved with conda.

However, I did not understand the UNIPROT_SEQS_PATH which you mentioned in msa.py.

UNIPROT_SEQS_PATH did not mentioned in config.py. Could you explain which file I should allocate to UNIPROT_SEQS_PATH? Did I miss anything from tutorial? In config.py I could only find UNIPROT_SEQ_PICKLE_PATH and UNIPROT_ALL_DB.

Becasue of missing UNIPROT_SEQS_PATH, I guess that's why I got empty _rawmsa.fasta output

Thank you in advance.

Xuan

**Comment by wangxuann1995** [comment]
Problem fixed

**Comment by liofoil** [comment]
Hello, I am trying to reproduce the code and encountered the same 'Undefined Symbol' issue. Could you please tell me how did you resolve it?
